move async from devDependencies -> dependencies
Otherwise the dependency isn't installed with the usual `npm install` (as installing with `--save-dev` isn't always possible/desirable).

This fixes the error:

```
$ grunt move
Loading "move.js" tasks...ERROR
>> Error: Cannot find module 'async'
Warning: Task "move" not found. Use --force to continue.

Aborted due to warnings.
```